In [2]:
import numpy as np

In [24]:
#1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.arange(1, 11)
print("1. Одновимірний масив з першими 10-ма натуральними числами: ", a)

1. Одновимірний масив з першими 10-ма натуральними числами:  [ 1  2  3  4  5  6  7  8  9 10]


In [25]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
b = np.zeros((3, 3), dtype = int)
print("2. Двовимірний масив 3x3, заповнений нулями:\n", b)

2. Двовимірний масив 3x3, заповнений нулями:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
#3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
c = np.random.randint(1, 11, size=(5, 5))
print("3. Двовимірний масив 5x5 з випадковими цілими числами від 1 до 10:\n", c)

3. Двовимірний масив 5x5 з випадковими цілими числами від 1 до 10:
 [[ 2  1  9  5  1]
 [10  7  3  5  2]
 [ 6  4  5  5  4]
 [ 8  2  2  8  8]
 [ 1  3 10 10  4]]


In [27]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
d = np.random.rand(4,4)
print("4. Двовимірний масив 4x4 з випадковими дійсними числами від 0 до 1:\n", d)

4. Двовимірний масив 4x4 з випадковими дійсними числами від 0 до 1:
 [[0.01525497 0.59884338 0.60380454 0.10514769]
 [0.38194344 0.03647606 0.89041156 0.98092086]
 [0.05994199 0.89054594 0.5769015  0.74247969]
 [0.63018394 0.58184219 0.02043913 0.21002658]]


In [28]:
#5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
e1 = np.random.randint(1, 11, size = 5)
e2 = np.random.randint(1, 11, size = 5)
e_sum = e1 + e2
print("5. Сума двох масивів:\nПерший масив: ", e1, "\nДругий масив: ", e2, "\nСума: ", e_sum)
e_sub = e1 - e2
print("Різниця двох масивів:\nПерший масив: ", e1, "\nДругий масив: ", e2, "\nРізниця: ", e_sub)
e_mult = e1 * e2
print("Добуток двох масивів:\nПерший масив: ", e1, "\nДругий масив: ", e2, "\nДобуток: ", e_mult)

5. Сума двох масивів:
Перший масив:  [ 4  6  1 10  4] 
Другий масив:  [7 4 5 8 7] 
Сума:  [11 10  6 18 11]
Різниця двох масивів:
Перший масив:  [ 4  6  1 10  4] 
Другий масив:  [7 4 5 8 7] 
Різниця:  [-3  2 -4  2 -3]
Добуток двох масивів:
Перший масив:  [ 4  6  1 10  4] 
Другий масив:  [7 4 5 8 7] 
Добуток:  [28 24  5 80 28]


In [29]:
#6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
f1 = np.random.randint(1, 11, size=(7))
f2 = np.random.randint(1, 11, size=(7))
f_scalar = np.dot(f1, f2)
print("6. Скалярний добуток двох масивів:\nПерший масив: ", f1, "\nДругий масив: ", f2, "\nСкалярний добуток: ", f_scalar)

6. Скалярний добуток двох масивів:
Перший масив:  [ 4 10  1  5  5  6  8] 
Другий масив:  [7 7 3 5 3 8 2] 
Скалярний добуток:  205


In [30]:
#7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
g1 = np.random.randint(1, 11, size=(2, 2))
g2 = np.random.randint(1, 11, size=(2, 3))
g_scalar = np.dot(g1, g2)
print("7. Скалярний добуток двох матриць:\nПерша матриця:\n", g1, "\nДруга матриця:\n", g2, "\nПоелементний добуток:\n", g_scalar)

7. Скалярний добуток двох матриць:
Перша матриця:
 [[7 7]
 [1 8]] 
Друга матриця:
 [[3 4 6]
 [5 3 5]] 
Поелементний добуток:
 [[56 49 77]
 [43 28 46]]


In [31]:
#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
h = np.random.randint(1, 10, size = (3, 3))
h_inv = np.linalg.inv(h)
print("8. Обернена матриця для випадкової матриці 3x3:\nВипадкова матриця:\n", h, "\nОбернена матриця:\n", h_inv)

8. Обернена матриця для випадкової матриці 3x3:
Випадкова матриця:
 [[4 8 1]
 [1 6 7]
 [7 6 7]] 
Обернена матриця:
 [[ 1.58603289e-17 -1.66666667e-01  1.66666667e-01]
 [ 1.40000000e-01  7.00000000e-02 -9.00000000e-02]
 [-1.20000000e-01  1.06666667e-01  5.33333333e-02]]


In [32]:
#9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
i = np.random.rand(4,4)
i_t = i.T
print("9. Транспонована матриця для випадкової матриці 4x4 з 0 та 1:\nВипадкова матриця:\n", i, "\nТранспонована матриця:\n", i_t)

9. Транспонована матриця для випадкової матриці 4x4 з 0 та 1:
Випадкова матриця:
 [[0.34038522 0.0920556  0.46349802 0.50869889]
 [0.08846017 0.52803522 0.99215804 0.39503593]
 [0.33559644 0.80545054 0.75434899 0.31306644]
 [0.63403668 0.54040458 0.29679375 0.1107879 ]] 
Транспонована матриця:
 [[0.34038522 0.08846017 0.33559644 0.63403668]
 [0.0920556  0.52803522 0.80545054 0.54040458]
 [0.46349802 0.99215804 0.75434899 0.29679375]
 [0.50869889 0.39503593 0.31306644 0.1107879 ]]


In [33]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
j1 = np.random.randint(1, 11, size=(3, 4))
j2 = np.random.randint(1, 11, size=4)
j_mult = np.dot(j1, j2)
print("10. Результат множення матриці 3x4 на вектор розміром 4:\nМатриця 3x4:\n", j1, "\nВектор розміром 4:\n", j2, "\nРезультат множення:\n", j_mult)

10. Результат множення матриці 3x4 на вектор розміром 4:
Матриця 3x4:
 [[10  9  6  3]
 [ 8  6 10  1]
 [10  9  7  3]] 
Вектор розміром 4:
 [1 6 4 3] 
Результат множення:
 [ 97  87 101]


In [34]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
k1 = np.random.rand(2, 3)
k2 = np.random.rand(3)
k_mult = np.dot(k1, k2)
print("11. Результат множення матриці 2x3 на вектор розміром 3:\nМатриця 2x3:\n", k1, "\nВектор розміром 3:\n", k2, "\nРезультат множення:\n", k_mult)

11. Результат множення матриці 2x3 на вектор розміром 3:
Матриця 2x3:
 [[0.8596183  0.62532376 0.98240783]
 [0.97650013 0.16669413 0.02317814]] 
Вектор розміром 3:
 [0.16074455 0.92349683 0.95354985] 
Результат множення:
 [1.6524383  0.33301008]


In [35]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
l1 = np.random.randint(1, 11, size=(2, 2))
l2 = np.random.randint(1, 11, size=(2, 2))
l_mult = l1 * l2
print("12. Поелементний добуток двох матриць 2x2:\nПерша матриця:\n", l1, "\nДруга матриця:\n", l2, "\nПоелементний добуток:\n", l_mult)

12. Поелементний добуток двох матриць 2x2:
Перша матриця:
 [[8 3]
 [2 3]] 
Друга матриця:
 [[8 2]
 [1 6]] 
Поелементний добуток:
 [[64  6]
 [ 2 18]]


In [36]:
#13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
m_scalar = np.dot(m1, m2)
print("13. Скалярний добуток двох матриць 2x2:\nПерша матриця:\n", m1, "\nДруга матриця:\n", m2, "\nСкалярний добуток:\n", m_scalar)

13. Скалярний добуток двох матриць 2x2:
Перша матриця:
 [[4 6]
 [3 7]] 
Друга матриця:
 [[ 2  2]
 [ 6 10]] 
Скалярний добуток:
 [[44 68]
 [48 76]]


In [37]:
#14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
n = np.random.randint(1, 101, size=(5, 5))
n_sum = np.sum(n)
print("14. Сума всіх елементів матриці 5x5:\nМатриця:\n", n, "\nСума елементів: ", n_sum)

14. Сума всіх елементів матриці 5x5:
Матриця:
 [[67 16 12 39 23]
 [56 58 88 52 49]
 [54 18 66 43 94]
 [45 17 52 55 56]
 [84 43 62 38 81]] 
Сума елементів:  1268


In [38]:
#15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
o1 = np.random.randint(1, 11, size=(4, 4))
o2 = np.random.randint(1, 11, size=(4, 4))
o_sub = o1 - o2
print("15. Різниця двох матриць 4x4:\nПерша матриця:\n", o1, "\nДруга матриця:\n", o2, "\nРізниця:\n", o_sub)

15. Різниця двох матриць 4x4:
Перша матриця:
 [[ 6  2  4  3]
 [ 4  2  1  7]
 [ 6  3  1  1]
 [10  2  6  3]] 
Друга матриця:
 [[ 4  7  2  5]
 [ 4  2  5  5]
 [10  6  7  4]
 [ 5  4  8  8]] 
Різниця:
 [[ 2 -5  2 -2]
 [ 0  0 -4  2]
 [-4 -3 -6 -3]
 [ 5 -2 -2 -5]]


In [39]:
#16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
p = np.random.rand(3, 3)
p1 = np.sum(p[0])
p2 = np.sum(p[1])
p3 = np.sum(p[2])
p_vec = np.array([p1, p2, p3])
print("16. Вектор суми рядків матриці 3x3:\nМатриця:\n", p, "\nВектор суми рядків:\n", p_vec)

16. Вектор суми рядків матриці 3x3:
Матриця:
 [[0.65503521 0.71103799 0.11353758]
 [0.13302869 0.45603906 0.15973623]
 [0.9616419  0.83761574 0.52016069]] 
Вектор суми рядків:
 [1.47961077 0.74880398 2.31941834]


In [40]:
#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
q = np.random.randint(1, 11, size = (3, 4))
q_quad = q ** 2
print("17. Квадрати елементів матриці 3x4:\nВипадкова матриця:\n", q, "\nКвадрати елементів:\n", q_quad)

17. Квадрати елементів матриці 3x4:
Випадкова матриця:
 [[ 7  6  1  9]
 [ 9  6 10  4]
 [ 3  9  8  2]] 
Квадрати елементів:
 [[ 49  36   1  81]
 [ 81  36 100  16]
 [  9  81  64   4]]


In [41]:
#18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
r = np.random.randint(1, 51, size = 4)
r_sqrt = np.sqrt(r)
print("18. Квадратні корені елементів масиву розміром 4:\nВипадковий масив:\n", r, "\nКвадратні корені елементів:\n", r_sqrt)

18. Квадратні корені елементів масиву розміром 4:
Випадковий масив:
 [ 5  1 24 20] 
Квадратні корені елементів:
 [2.23606798 1.         4.89897949 4.47213595]


In [1]:
#Додаткові завдання

In [7]:
#1
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
A[A % 2 == 1] = -1
print(A)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [23]:
#2
B = np.array([1, 2, 3, 4, 5, 6])
print(B)
B_2d = arr.reshape(2, -1)
print(B_2d)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [22]:
#3
aa = np.array([[1, 2, 3],
              [4, 5, 6]])
bb = np.array([[7, 8, 9],
              [10, 11, 12]])
cc = np.vstack((aa, bb))
print(cc)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
#4
C = np.array([1,2,3])
C_result = np.concatenate((np.repeat(C, len(C)),
                          np.tile(C, len(C))))
print(C_result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [21]:
#5
D1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
D2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
D_common = np.intersect1d(D1, D2)
print(D_common)

[2 4]


In [14]:
#6
np.random.seed(100)
E = np.random.uniform(1, 50, 20)
print(E)
E_indices = np.argsort(E)[-5:][::-1]
print(E_indices)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[15 10  3  7 18]


In [15]:
#7
F = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])

# Remove NaN values
F_result = F[~np.isnan(F)]

print(F_result)

[1. 2. 3. 5. 6. 7.]


In [20]:
#8
G1 = np.array([1, 2, 3, 4, 5])
G2 = np.array([4, 5, 6, 7, 8])

# Euclidean distance
G_distance = np.linalg.norm(G1 - G2)

print(G_distance)

6.708203932499369


In [19]:
#9
H = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
H_indices = np.where(H == 1)[0]
H_fifth_index = H_indices[4]
print(H_fifth_index)

8


In [18]:
#10
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print("a:", a)
_, idx = np.unique(a, return_index=True)
mask = np.ones_like(a, dtype=bool)
mask[idx] = False
print(mask)

a: [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]
